apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-migration
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        app: {{ include "chart.fullname" . }}-migration
    spec:
      containers:
      - name: db-migration-container
        image: "{{ .Values.image.backendRepository }}:{{ .Values.image.tag }}"
        command: ["./main", "migrate"] 
        imagePullPolicy: IfNotPresent
        {{- include "chart.envFrom" . | nindent 8 }}
      restartPolicy: Never
  ttlSecondsAfterFinished: 30
