{{ $app_name := env "APP_NAME" | default "golang-app"}}

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: mysql-db
  namespace: {{ $app_name }}
  chart: bitnami/mysql
  version: "10.2.2"
  values:
  - ./values/mysql/values.yaml
