name: Sample SRE Project Pipeline

on:
    push: 
        branches:
            - main

jobs:
    test-and-deploy:
        name: Test and Deploy
        runs-on: ubuntu-latest
        services:
          mysql:
            image: mysql:latest
            env:
              MYSQL_ROOT_PASSWORD: root-secret
              MYSQL_USER: admin
              MYSQL_PASSWORD: secret
              MYSQL_DATABASE: testdb
            ports:
              - 3306:3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: |
                cd backend && go mod vendor
            
            - name: DB Migration
              env:
                DB_HOST: localhost
                DB_PORT: 3306
                DB_NAME: testdb
                DB_USERNAME: admin
                DB_PASSWORD: secret
              run: cd backend && go run main.go migrate
        
            - name: Run unit tests
              run: |
                cd backend/test
                go test

            - name: Extract and append changelog
              run: |
                echo "Will work on this later"
